USE [Volejbal]
GO

/****** Object:  Table [dbo].[Sezona]    Script Date: 16.11.2025 18:30:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Sezona](
	[id_sezona] [int] NOT NULL,
	[rok] [int] NOT NULL,
	[nazev] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_sezona] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


